### ISSUE TITLE
Alternative download option

### ISSUE THREAD

**Issue by FlorentF9** [yangchunhua52013/CQU-BPMDD#1]
Thank you for making this dataset available! However, I was not able to download the data using the Baidu hosting platform - whatever I do, it shows error messages. Could you please provide an alternative way to access the dataset?

**Comment by ychxff** [comment]
Thank you for your opinion. We did not consider the problem that Baidu Cloud Disk might not be accessible in different countries or regions at the time. You can optionally turn on a proxy to access the source URL of the dataset. In addition, we are currently uploading this dataset to Google Cloud Disk for access. The upload is expected to be completed within 72 hours. Thank you again for your opinion.

**Comment by FlorentF9** [comment]
Thank you for your very quick answer! (I think a baidu membership is required).
It will make the dataset more accessible for users outside of China.

**Comment by ychxff** [comment]
Thanks again for your valuable suggestion, the dataset has been uploaded to Google Cloud Drive,  and you can click to view or download it (in README).
